.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. pivotalcoin_qt test_pivotalcoin_qt
clean: FORCE
	$(MAKE) -C .. pivotalcoin_qt_clean test_pivotalcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_pivotalcoin_qt_check
pivotalcoin-qt pivotalcoin-qt.exe: FORCE
	 $(MAKE) -C .. pivotalcoin_qt
